(define-module (main)
  #:use-module (gl)
  #:use-module (gl enums)  
  #:use-module (glut))

(define (display)
  (set-gl-clear-color 0 0 0 1)
  (gl-clear (clear-buffer-mask color-buffer))
  (gl-begin (begin-mode quads)
            (gl-color 0 0 1)
            (gl-vertex -0.5 -0.5)
            (gl-vertex  0.5 -0.5)
            (gl-vertex  0.5  0.5)
            (gl-vertex -0.5  0.5)))

(define-public (doit)
  (initialize-glut #:window-size '(320 . 320)
                    #:window-position '(50 . 50))
  (let ((window (make-window "OpenGL Scheme Test")))
    (set-display-callback display)
    (glut-main-loop)))
